#!/bin/bash

# Array berisi daftar file yang ingin dihapus
files=(
  "/usr/share/help/C/fdl/index.docbook"
  "/usr/share/help/C/gpl/index.docbook"
  "/usr/share/help/C/lgpl/index.docbook" 
  "/usr/share/help/ar/fdl/index.docbook" 
  "/usr/share/help/ar/gpl/index.docbook" 
  "/usr/share/help/ar/lgpl/index.docbook" 
  "/usr/share/help/ca/fdl/index.docbook" 
  "/usr/share/help/ca/gpl/index.docbook" 
  "/usr/share/help/ca/lgpl/index.docbook" 
  "/usr/share/help/cs/fdl/index.docbook" 
  "/usr/share/help/cs/gpl/index.docbook" 
  "/usr/share/help/cs/lgpl/index.docbook" 
  "/usr/share/help/de/fdl/index.docbook" 
  "/usr/share/help/de/gpl/index.docbook" 
  "/usr/share/help/de/lgpl/index.docbook"
  "/usr/share/help/el/fdl/index.docbook" 
  "/usr/share/help/el/gpl/index.docbook" 
  "/usr/share/help/el/lgpl/index.docbook" 
  "/usr/share/help/es/fdl/index.docbook" 
  "/usr/share/help/es/gpl/index.docbook" 
  "/usr/share/help/es/lgpl/index.docbook" 
  "/usr/share/help/eu/fdl/index.docbook" 
  "/usr/share/help/eu/gpl/index.docbook" 
  "/usr/share/help/eu/lgpl/index.docbook" 
  "/usr/share/help/fi/gpl/index.docbook" 
  "/usr/share/help/fi/lgpl/index.docbook" 
  "/usr/share/help/fr/fdl/index.docbook" 
  "/usr/share/help/fr/gpl/index.docbook" 
  "/usr/share/help/fr/lgpl/index.docbook" 
  "/usr/share/help/gl/fdl/index.docbook" 
  "/usr/share/help/gl/gpl/index.docbook" 
  "/usr/share/help/gl/lgpl/index.docbook" 
  "/usr/share/help/hr/fdl/index.docbook" 
  "/usr/share/help/hr/gpl/index.docbook" 
  "/usr/share/help/hr/lgpl/index.docbook" 
  "/usr/share/help/hu/fdl/index.docbook" 
  "/usr/share/help/hu/gpl/index.docbook"
  "/usr/share/help/hu/lgpl/index.docbook" 
  "/usr/share/help/ko/fdl/index.docbook" 
  "/usr/share/help/ko/gpl/index.docbook" 
  "/usr/share/help/ko/lgpl/index.docbook" 
  "/usr/share/help/nds/gpl/index.docbook" 
  "/usr/share/help/oc/fdl/index.docbook" 
  "/usr/share/help/oc/gpl/index.docbook" 
  "/usr/share/help/oc/lgpl/index.docbook" 
  "/usr/share/help/pa/gpl/index.docbook" 
  "/usr/share/help/pa/lgpl/index.docbook" 
  "/usr/share/help/pt_BR/fdl/index.docbook" 
  "/usr/share/help/pt_BR/gpl/index.docbook" 
  "/usr/share/help/pt_BR/lgpl/index.docbook" 
  "/usr/share/help/sl/fdl/index.docbook" 
  "/usr/share/help/sl/gpl/index.docbook" 
  "/usr/share/help/sl/lgpl/index.docbook" 
  "/usr/share/help/sr/fdl/index.docbook" 
  "/usr/share/help/sr/gpl/index.docbook" 
  "/usr/share/help/sr@latin/gpl/index.docbook" 
  "/usr/share/help/sv/fdl/index.docbook" 
  "/usr/share/help/sv/gpl/index.docbook" 
  "/usr/share/help/sv/lgpl/index.docbook" 
  "/usr/share/help/tr/fdl/index.docbook" 
  "/usr/share/help/tr/gpl/index.docbook" 
  "/usr/share/help/tr/lgpl/index.docbook" 
  "/usr/share/help/uk/fdl/index.docbook" 
  "/usr/share/help/uk/gpl/index.docbook" 
  "/usr/share/help/uk/lgpl/index.docbook" 
  "/usr/share/help/vi/fdl/index.docbook" 
  "/usr/share/help/vi/gpl/index.docbook" 
  "/usr/share/help/vi/lgpl/index.docbook" 
  "/usr/share/help/zh_CN/fdl/index.docbook" 
  "/usr/share/help/zh_CN/gpl/index.docbook" 
  "/usr/share/help/zh_CN/lgpl/index.docbook" 
)

# Loop untuk setiap file dalam array
for file in "${files[@]}"; do
  # Periksa apakah file tersebut ada
  if [ -f "$file" ]; then
    # Hapus file
    # Make su, mending lu hati2 dah
    sudo rm -f "$file" 
    echo "File '$file' berhasil dihapus."
  else
    # Tampilkan pesan error
    echo "File '$file' tidak ditemukan."
  fi
done
